agent:
  llm_model: gpt-4o-mini
  system_prompt: You are a helpful AI assistant with access to a knowledge base. Answer
    questions based on the provided context.
edited: true
knowledge:
  chunk_overlap: 200
  chunk_size: 1000
  doclingPresets: standard
  embedding_model: text-embedding-3-small
provider:
  api_key: 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
  model_provider: openai
