services:
  opensearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: os
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}
    ports:
      - "9200:9200"
      - "9600:9600"

  dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    container_name: osdash
    depends_on:
      - opensearch
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
      OPENSEARCH_USERNAME: "admin"
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
    ports:
      - "5601:5601"

  gendb:
    image: phact/gendb:latest
    #build:
      #context: .
      #dockerfile: Dockerfile.app
    container_name: gendb-app
    depends_on:
      - opensearch
      - langflow
    environment:
      - OPENSEARCH_HOST=opensearch
      - LANGFLOW_URL=http://langflow:7860
      - LANGFLOW_SECRET_KEY=${LANGFLOW_SECRET_KEY}
      - FLOW_ID=${FLOW_ID}
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./frontend/src:/app/frontend/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ./documents:/app/documents
    gpus: all
    platform: linux/amd64

  langflow:
    volumes:
      - ./flows:/app/flows
    #image: langflow:1.5.0.post1
    image: phact/langflow:responses
    container_name: langflow
    ports:
      - "7860:7860"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGFLOW_LOAD_FLOWS_PATH=/app/flows
      - LANGFLOW_SECRET_KEY=${LANGFLOW_SECRET_KEY}
