apiVersion: v2
name: bomarag-operator
description: A Helm chart for the BomaRAG Kubernetes Operator
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bomarag
  - operator
  - kubernetes
home: https://github.com/ABISHAIMWANJA/bomarag
sources:
  - https://github.com/ABISHAIMWANJA/bomarag
maintainers:
  - name: BomaRAG Team
    url: https://github.com/ABISHAIMWANJA/bomarag

