{{- if .Values.global.filenet.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openrag.fullname" . }}-filenet-mcp
  namespace: {{ include "openrag.namespace" . }}
  labels:
    {{- include "openrag.filenetMcp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.filenet.mcp.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openrag.filenetMcp.selectorLabels" . | nindent 4 }}
{{- end }}
