{{- if .Values.global.filenet.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openrag.fullname" . }}-filenet
  namespace: {{ include "openrag.namespace" . }}
  labels:
    {{- include "openrag.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.global.filenet.username | quote }}
  password: {{ .Values.global.filenet.password | quote }}
  {{- if .Values.global.filenet.authToken }}
  auth-token: {{ .Values.global.filenet.authToken | quote }}
  {{- end }}
{{- end }}
