# OpenRAG Configuration File
provider:
  model_provider: "openai" # openai, anthropic, azure, etc.
  api_key: "your-api-key" # or use OPENAI_API_KEY env var

knowledge:
  embedding_model: "text-embedding-3-small"
  chunk_size: 1000
  chunk_overlap: 200
  ocr: true
  picture_descriptions: false

agent:
  llm_model: "gpt-4o-mini"
  system_prompt: "You are a helpful AI assistant..."