#!/usr/bin/env bash
set -euo pipefail

# Generate strong secrets for production .env values.
# Usage:
#   scripts/generate-secrets.sh
#   scripts/generate-secrets.sh --write .env.generated

write_file=""
if [[ "${1:-}" == "--write" ]]; then
  write_file="${2:-}"
  if [[ -z "$write_file" ]]; then
    echo "ERROR: missing output file path for --write" >&2
    exit 1
  fi
fi

gen_b64() {
  local bytes="$1"
  openssl rand -base64 "$bytes" | tr -d '\n'
}

gen_password() {
  # Generates a password compatible with OpenSearch complexity rules.
  python - <<'PY'
import secrets, string
upper = string.ascii_uppercase
lower = string.ascii_lowercase
digits = string.digits
special = "!@$%^&*()-_=+"
alphabet = upper + lower + digits + special
while True:
    s = "".join(secrets.choice(alphabet) for _ in range(24))
    if (any(c in upper for c in s) and any(c in lower for c in s)
        and any(c in digits for c in s) and any(c in special for c in s)):
        print(s)
        break
PY
}

OPENRAG_ENCRYPTION_KEY="$(gen_b64 32)"
SESSION_SECRET="$(gen_b64 48)"
LANGFLOW_SECRET_KEY="$(gen_b64 48)"
OPENSEARCH_PASSWORD="$(gen_password)"
LANGFLOW_SUPERUSER_PASSWORD="$(gen_password)"
VALKEY_PASSWORD="$(gen_password)"

output="$(cat <<EOF
# Generated by scripts/generate-secrets.sh
OPENRAG_ENCRYPTION_KEY=${OPENRAG_ENCRYPTION_KEY}
SESSION_SECRET=${SESSION_SECRET}
LANGFLOW_SECRET_KEY=${LANGFLOW_SECRET_KEY}
OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
LANGFLOW_SUPERUSER_PASSWORD=${LANGFLOW_SUPERUSER_PASSWORD}
VALKEY_PASSWORD=${VALKEY_PASSWORD}
EOF
)"

if [[ -n "$write_file" ]]; then
  {
    printf "\n"
    printf "%s\n" "$output"
  } >> "$write_file"
  echo "Secrets appended to: $write_file"
else
  printf "%s\n" "$output"
fi
