name: Integration Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: [self-hosted, linux, ARM64, langflow-ai-arm64-2]
    env:
      # Prefer repository/environment variable first, then secret, then a sane fallback
      OPENSEARCH_PASSWORD: ${{ vars.OPENSEARCH_PASSWORD || secrets.OPENSEARCH_PASSWORD || 'OpenRag#2025!' }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - run: df -h
        #- name: "node-cleanup"
        #run: |
        #  sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        #  sudo docker image prune --all --force
        #  sudo docker builder prune -a
      - run: df -h
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v3
        with:
          version: latest

      - name: Python version
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync --group dev --extra torch-cu128

      - name: Run integration tests
        env:
          OPENSEARCH_HOST: localhost
          OPENSEARCH_PORT: 9200
          OPENSEARCH_USERNAME: admin
          OPENSEARCH_PASSWORD: ${{ env.OPENSEARCH_PASSWORD }}
          LOG_LEVEL: DEBUG
          # Force no-auth mode so tests bypass OAuth
          GOOGLE_OAUTH_CLIENT_ID: ""
          GOOGLE_OAUTH_CLIENT_SECRET: ""
          # Disable startup ingest noise unless a test enables it
          DISABLE_STARTUP_INGEST: "true"
        run: |
          make test-ci
          echo "Keys directory after tests:"
          ls -la keys/ || echo "No keys directory"
